# Generated by Django 4.2.27 on 2026-02-07 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="질병명"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cardiovascular", "심혈관"),
                            ("endocrine", "내분비"),
                            ("respiratory", "호흡기"),
                            ("digestive", "소화기"),
                            ("musculoskeletal", "근골격"),
                            ("neurological", "신경"),
                            ("mental", "정신건강"),
                            ("dermatological", "피부"),
                            ("immune", "면역"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "keywords",
                    models.JSONField(default=list, verbose_name="검색 키워드"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "질병/증상",
                "verbose_name_plural": "질병/증상 목록",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrustedChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="YouTube 채널 ID"
                    ),
                ),
                (
                    "channel_title",
                    models.CharField(max_length=200, verbose_name="채널명"),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("doctor", "의사"),
                            ("pharmacist", "약사"),
                            ("public", "공공기관"),
                            ("expert", "전문가"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="채널 유형",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "신뢰 채널",
                "verbose_name_plural": "신뢰 채널 목록",
                "ordering": ["channel_type", "channel_title"],
            },
        ),
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=list,
                        help_text='예: [{"name": "고혈압", "category": "심혈관"}]',
                        verbose_name="추론된 질병/증상",
                    ),
                ),
                (
                    "search_queries",
                    models.JSONField(
                        default=list,
                        help_text="질병 기반 생성된 검색 키워드 목록",
                        verbose_name="YouTube 검색 키워드",
                    ),
                ),
                (
                    "last_analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 분석 일시"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "건강 프로필",
                "verbose_name_plural": "건강 프로필 목록",
            },
        ),
        migrations.CreateModel(
            name="CachedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="YouTube 영상 ID"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("thumbnail_url", models.URLField(verbose_name="썸네일 URL")),
                (
                    "channel_title",
                    models.CharField(max_length=200, verbose_name="채널명"),
                ),
                ("channel_id", models.CharField(max_length=50, verbose_name="채널 ID")),
                ("published_at", models.DateTimeField(verbose_name="영상 게시일")),
                (
                    "view_count",
                    models.PositiveIntegerField(default=0, verbose_name="조회수"),
                ),
                (
                    "content_category",
                    models.CharField(
                        choices=[
                            ("diet", "식이요법"),
                            ("exercise", "운동"),
                            ("lifestyle", "생활습관"),
                            ("medical", "전문의 설명"),
                            ("general", "일반 건강"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="콘텐츠 카테고리",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="검색 키워드"
                    ),
                ),
                (
                    "is_from_trusted_channel",
                    models.BooleanField(default=False, verbose_name="신뢰 채널 영상"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conditions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="videos",
                        to="health.healthcondition",
                        verbose_name="관련 질병",
                    ),
                ),
            ],
            options={
                "verbose_name": "캐시 영상",
                "verbose_name_plural": "캐시 영상 목록",
                "ordering": ["-is_from_trusted_channel", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="health.cachedvideo",
                        verbose_name="영상",
                    ),
                ),
            ],
            options={
                "verbose_name": "영상 북마크",
                "verbose_name_plural": "영상 북마크 목록",
                "ordering": ["-created_at"],
                "unique_together": {("user", "video")},
            },
        ),
    ]
