# Generated by Django 4.2.28 on 2026-03-18 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LifestyleTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="대상 날짜")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diet", "식이요법"),
                            ("exercise", "운동"),
                            ("lifestyle", "생활습관"),
                            ("mental", "정서 관리"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="팁 제목")),
                ("content", models.TextField(verbose_name="팁 내용")),
                (
                    "emoji",
                    models.CharField(
                        default="💡", max_length=10, verbose_name="아이콘 이모지"
                    ),
                ),
                (
                    "condition_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="관련 질병명"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifestyle_tips",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "라이프스타일 팁",
                "verbose_name_plural": "라이프스타일 팁 목록",
                "ordering": ["date", "category"],
                "unique_together": {("user", "date", "category")},
            },
        ),
    ]
