# Generated by Django 4.2.27 on 2026-01-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="연락처 이름")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="전화번호"),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("guardian", "보호자"),
                            ("hospital", "병원/의료기관"),
                            ("emergency", "119 응급서비스"),
                            ("other", "기타"),
                        ],
                        default="guardian",
                        max_length=15,
                        verbose_name="연락처 유형",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(default=1, verbose_name="우선순위"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비상 연락처",
                "verbose_name_plural": "비상 연락처 목록",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("reminder", "복약 리마인더"),
                            ("warning", "미복약 경고"),
                            ("emergency", "비상 알림"),
                        ],
                        default="reminder",
                        max_length=15,
                        verbose_name="알림 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("sent", "발송됨"),
                            ("cancelled", "취소됨"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="상태",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="알림 제목")),
                ("message", models.TextField(verbose_name="알림 내용")),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Celery 태스크 ID"
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="예약 시간")),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="발송 시간"
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="재시도 횟수"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="에러 메시지"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medication_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="medications.medicationlog",
                        verbose_name="복약 기록",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="알림 수신자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대상 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비상 알림",
                "verbose_name_plural": "비상 알림 목록",
                "ordering": ["-scheduled_at"],
            },
        ),
    ]
