# Generated by Django 4.2.27 on 2026-01-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_emergency_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("relation", models.CharField(max_length=50, verbose_name="관계")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                (
                    "notify_by_email",
                    models.BooleanField(default=True, verbose_name="이메일 알림"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="주 연락처 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "비상 연락처",
                "verbose_name_plural": "비상 연락처 목록",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
