# Generated by Django 4.2.27 on 2026-01-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_emergencycontact"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6, unique=True, verbose_name="초대 코드"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료 시간")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_invites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invite_codes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "초대 코드",
                "verbose_name_plural": "초대 코드 목록",
            },
        ),
    ]
