# Generated by Django 4.2.27 on 2026-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "복약자"),
                    ("senior", "시니어"),
                    ("guardian", "보호자"),
                ],
                default="patient",
                max_length=10,
                verbose_name="역할",
            ),
        ),
    ]
