# Generated by Django 4.2.27 on 2026-03-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_senior_into_patient"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False, verbose_name="프리미엄 여부"),
        ),
        migrations.AddField(
            model_name="user",
            name="premium_until",
            field=models.DateTimeField(
                blank=True,
                help_text="null이면 무기한 프리미엄",
                null=True,
                verbose_name="프리미엄 만료일",
            ),
        ),
    ]
