# Generated by Django 4.2.27 on 2026-01-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="약품명")),
                ("description", models.TextField(blank=True, verbose_name="복용 설명")),
                (
                    "dosage",
                    models.CharField(blank=True, max_length=50, verbose_name="복용량"),
                ),
                (
                    "prescription_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="prescriptions/",
                        verbose_name="처방전 이미지",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "복용 약품",
                "verbose_name_plural": "복용 약품 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("morning", "아침"),
                            ("noon", "점심"),
                            ("evening", "저녁"),
                            ("night", "취침 전"),
                            ("custom", "사용자 지정"),
                        ],
                        default="morning",
                        max_length=10,
                        verbose_name="복용 시간대",
                    ),
                ),
                ("scheduled_time", models.TimeField(verbose_name="예정 시간")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="medications.medication",
                        verbose_name="약품",
                    ),
                ),
            ],
            options={
                "verbose_name": "복약 스케줄",
                "verbose_name_plural": "복약 스케줄 목록",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="MedicationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_datetime", models.DateTimeField(verbose_name="예정 일시")),
                (
                    "taken_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="복용 일시"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("taken", "복용 완료"),
                            ("missed", "미복용"),
                            ("skipped", "건너뜀"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="알림 태스크 ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="medications.medicationschedule",
                        verbose_name="스케줄",
                    ),
                ),
            ],
            options={
                "verbose_name": "복약 기록",
                "verbose_name_plural": "복약 기록 목록",
                "ordering": ["-scheduled_datetime"],
            },
        ),
    ]
