# Generated by Django 4.2.27 on 2026-01-09 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={
                "ordering": ["group", "-created_at"],
                "verbose_name": "복용 약품",
                "verbose_name_plural": "복용 약품 목록",
            },
        ),
        migrations.CreateModel(
            name="MedicationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="증상/질환명")),
                (
                    "color",
                    models.CharField(
                        default="mint", max_length=20, verbose_name="구분 색상"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medication_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "약품 그룹",
                "verbose_name_plural": "약품 그룹 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="medication",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medications",
                to="medications.medicationgroup",
                verbose_name="약품 그룹",
            ),
        ),
    ]
