# Generated by Django 4.2.27 on 2026-01-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0003_medicationgroup_is_severe"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="days_supply",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="처방 일수"
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="복용 시작일"),
        ),
    ]
